### ISSUE TITLE
Provide gymnasium0.28.1 for python3.12

### ISSUE THREAD

**Issue by mattip** [conda-forge/gymnasium-feedstock#38]
### Comment:

This feedstock first supports python3.12 in version 0.29.1.

Over at [the ray feedstock](https://github.com/conda-forge/ray-packages-feedstock/pull/172#issuecomment-2314226889), I am trying to add support for python3.12. Ray pins gymnasium to 0.28.1, and I am hesitant to change that locally to 0.29.1 in the feedstock since it is difficult to test all the different uses of ray + gymnasium. I fear something might subtly break by using the wrong version. Could one of the maintainers cut a 0.28.1 package for python3.12?

**Comment by h-vetinari** [comment]
Upstream gymnasium 0.28 [does not](https://github.com/Farama-Foundation/Gymnasium/blob/v0.28.1/pyproject.toml#L15-L26) support python 3.12, so this doesn't seem like a good idea to me from the outset.

I _can_ create a branch at 374a8b1cf806b19cc1abaee779597dfc9cc66dab for you, but a lot of changes have landed since then, and you'll likely have to recreate them (+ revalidate). IMO this risks being a big time sink, but if you want to give it a shot, let me know and I'll create the branch.

My humble suggestion would be to update upstream ray to gymnasium 0.29, wait for a new release (given ray's new higher release cadence), and then retry python 3.12 support.

**Comment by mattip** [comment]
> Upstream gymnasium 0.28 [does not](https://github.com/Farama-Foundation/Gymnasium/blob/v0.28.1/pyproject.toml#L15-L26) support python 3.12, so this doesn't seem like a good idea to me from the outset.

Ahh. Thanks for checking that

> update upstream ray to gymnasium 0.29

Makes sense. I will close this.
